### ISSUE TITLE
Server crashes when agents are scaled up

### ISSUE THREAD

**Issue by pturley** [ThoughtWorks-AELab/dockerized-ci#3]
* docker-compose up -d
* Wait for server to come up
* docker-compose scale go-agent=10
* docker-compose logs
* See go-server killed.  

I think it is running out of memory or something

**Comment by jimarnold** [comment]
I had to create a docker-machine VM with more memory:

docker-machine create --driver virtualbox --virtualbox-memory "8096"

**Comment by pturley** [comment]
Ahhh nice. Probably add that to the readme. Well once we create it that is.

**Comment by pturley** [comment]
Yup, it works
